### ISSUE TITLE
CultureInfo is not respected

### ISSUE THREAD

**Issue by mikechamberlain** [kbilsted/StatePrinter#56] opened 2018-06-24 17:30 UTC
On the master branch in the `CultureTests.CultureDependentPrinting_us` test, the test fails on my machine with the result:

```
String lengths are both 21. Strings differ at index 1.
Expected: "2/28/2010 10:10:59 PM"
But was:  "28-Feb-10 10:10:59 PM"
```

My machine uses the Thailand culture.

**Comment by kbilsted** [comment] 2018-06-25 15:12
Your guess is as good as mine. Perhaps that particular culture info is not installed on your machine? I'd be great if you can dig up an answer. Currently the test is run on a danish windows and an uk/us machine (appveyor)

**Comment by kbilsted** [comment] 2018-07-09 13:24
@mikechamberlain  any progress on this? is said culture installed on the machine?

**Comment by kbilsted** [comment] 2019-01-16 21:14
closing can't reproduce

**Closed by kbilsted** 2019-01-16 21:14 UTC
Labels: Help wanted, bug
